name: AWS Deploy

on: workflow_dispatch

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-2'

      - name: Set current date as env variable
        run: echo "::set-env name=NOW::$(date +'%Y-%m-%dT%H-%M-%S')"

      - name: Copy app jar to S3 bucket
        run: aws s3 cp ./dynamodb-sqs-app/target/dynamodb-sqs-app-0.0.1-SNAPSHOT.jar s3://app-jar-bucket-demo/dynamodb-sqs-app-$GITHUB_SHA-$NOW.jar

      - name: Copy function jar to S3 bucket
        run: aws s3 cp ./s3-lambda/target/s3-lambda-0.0.1-SNAPSHOT.jar s3://app-jar-bucket-demo/s3-lambda-$GITHUB_SHA-$NOW.jar

      - name: Copy stack template to S3 bucket
        run: |
          aws s3 rm s3://app-jar-bucket-demo/stack-template.json \
          && aws s3 cp ./stack-template.json s3://app-jar-bucket-demo/stack-template.json

      - name: Deploy stack
        run: |
          aws cloudformation deploy \
          --stack-name training-demo-stack \
          --template-file stack-template.json \
          --s3-bucket app-jar-bucket-demo \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides  JarVersion=$GITHUB_SHA-$NOW \
          --no-fail-on-empty-changeset \
          --s3-prefix stack
